source 'http://rubygems.org'

gem 'rails', '3.0.7'
gem 'rake'
# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'
gem 'thin'
gem 'sqlite3'

#image attachment management
gem "paperclip"

#gem 'jquery-rails'

# authentication framework
gem 'authlogic', :git => 'git://github.com/odorcicd/authlogic.git', :branch => 'rails3'
gem "rails3-generators"

# slim-lang HTML templating engine
gem "slim", :require => "slim"
gem "slim-rails"

gem "formtastic"
gem "sass"
#coffeescript support
gem "barista"
#social networking integration
gem 'omniauth', '>0.1.6'

#gem 'facebooker'

